version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recruitment_task
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: recruitment_task
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/:z
    working_dir: /app
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      SERVICE_NAME: postgres
    volumes:
      - ./docker/db:/var/lib/postgresql/data:z
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge